### ISSUE TITLE
jest open handle with winston log enricher

### ISSUE THREAD

**Issue by k2xl** [newrelic/newrelic-node-log-extensions#84]
```
import newrelicFormatter from '@newrelic/winston-enricher';
import winston, { createLogger, format, transports } from 'winston';
import isLocal from '../lib/isLocal';

const errorStackTracerFormat = winston.format(info => {
  if (info.meta && info.meta instanceof Error) {
    info.message = `${info.message} ${info.meta.stack}`;
  }

  return info;
});

const devLoggerOptions = {
  level: 'info',
  format: format.combine(
    format.errors({ stack: true }),
    format.colorize(),
    errorStackTracerFormat(),
    format.simple(),
  ),
  transports: [
    new transports.Console(),
  ],
};
let options = devLoggerOptions;

if (!isLocal()) {
  const newrelicWinstonFormatter = newrelicFormatter(winston);

  options = {
    ...devLoggerOptions,
    level: 'info',
    format: format.combine(
      winston.format.splat(),
      format.errors({ stack: true }),
      newrelicWinstonFormatter(),
    ),
  };
}

export const logger = createLogger({
  ...options,
});

```

Above you can see I switch on whether i'm in dev or prod on whether to use the newrelicWinstonFormatter.

However, running jest test with `--detectOpenHandles` I always get:

```
  at Agent.wrappedCreateConnection [as createConnection] (node_modules/newrelic/lib/instrumentation/core/http.js:485:27)
      at Object.wrappedRequest [as request] (node_modules/newrelic/lib/instrumentation/core/http.js:412:22)
      at RemoteMethod._request (node_modules/newrelic/lib/collector/remote-method.js:325:21)
      at RemoteMethod._safeRequest (node_modules/newrelic/lib/collector/remote-method.js:268:8)
      at makeRequest (node_modules/newrelic/lib/collector/remote-method.js:178:14)
      at RemoteMethod._post (node_modules/newrelic/lib/collector/remote-method.js:173:5)
      at RemoteMethod.onSerialize (node_modules/newrelic/lib/collector/remote-method.js:115:12)
      at RemoteMethod.serialize (node_modules/newrelic/lib/collector/remote-method.js:71:10)
      at RemoteMethod.invoke (node_modules/newrelic/lib/collector/remote-method.js:109:8)
      at CollectorAPI._login (node_modules/newrelic/lib/collector/api.js:224:22)
      at CollectorAPI.connect (node_modules/newrelic/lib/collector/api.js:209:8)
      at Agent.start (node_modules/newrelic/lib/agent.js:242:18)
      at createAgent (node_modules/newrelic/index.js:151:9)
      at initialize (node_modules/newrelic/index.js:81:15)
      at Object.<anonymous> (node_modules/newrelic/index.js:36:3)
      at Object.<anonymous> (node_modules/@newrelic/winston-enricher/index.js:14:18)
```

The reason it seems is that just on importing `import newrelicFormatter from '@newrelic/winston-enricher';` that act alone is trying to connect to some http server.

I wouldn't mind this if there was a way to close the connection after the test but I'm not sure how to properly do that. Ideally this connection would have been made only on the function call not the import.

Logs work fine, it's just an annoying thing I notice with our tests having a hanging handle

**Comment by jordigh** [comment]
Using the Winston log enricher indicates that you want to use the New Relic agent, as it's a dependency of the enricher. For a test, you probably want to disable the agent, so it doesn't attempt to connect to anything.

https://docs.newrelic.com/docs/apm/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration/#agent-enabled

I believe this should be sufficient for use case. If you find a further bug, feel free to reopen this issue.
